### ISSUE TITLE
Typo, BPM

### ISSUE THREAD

**Issue by githubjonas** [arnaud-carre/LSPlayer#13]
Cheers! 🍻  Nice work! Just noticed a typo in the output.
"BMP" => "BPM"
https://github.com/arnaud-carre/LSPlayer/blob/a6aa2aac8f29b53415c7971ee6a5af03d5ba26b4/src/LSPEncoder.cpp#L411C52-L411C54

**Comment by arnaud-carre** [comment]
thanks!
