### ISSUE TITLE
LSP doesnt work outside the os?

### ISSUE THREAD

**Issue by Ozzyboshi** [arnaud-carre/LSPlayer#16]
I dont know if anyone here experienced this problem, if you use LSP outside the OS the music is not reproduced, it seems the playback routine is correctly executed on cia interrupt but I dont hear anything from the speakers.

In order to reproduce this just create a bootable adf file with exe2adf, put your demo that should playing the lsp music inside and launch it automatically with startup sequence.
The same executable, if launched from wb via CLI works regularly.

I am not sure this is LSP fault, it could be my code not using LSP in the right way but... just to know if this is has already been reported or not.

**Comment by arnaud-carre** [comment]
This shouldn't be related to LSP. It has already be used both in some OS compatible exe and also non-system demos.
