### ISSUE TITLE
CIA interrupt flag cleared in wrong order

### ISSUE THREAD

**Issue by chrisly42** [arnaud-carre/LSPlayer#6]
I can't take credit for this, it was mentioned in [this EAB thread](https://eab.abime.net/showthread.php?t=110353).

```
.LSP_MainIrq:
			move.w	#$2000,$dff09c
			btst.b	#0,$bfdd00
			beq.s	.skipa

.LSP_DmaconIrq:
			move.w	#$2000,$dff09c
			btst.b	#1,$bfdd00
			beq.s	.skipb
```

Apparently, this order can retrigger the CIA interrupt a second time because the CIA edge interrupt has not been cleared by the btst and thus the intreq might be set again (maybe this doesn't happen on all CPU configurations due to internal race conditions). I haven't come across this as I haven't been using the CIA timer one, but I wanted to mention it here.

**Comment by arnaud-carre** [comment]
interesting thread! I asked question in amiga forum, i'm curious. Thank you for the heads-up

**Comment by arnaud-carre** [comment]
fixed in recent LSP version, thanks!
