### ISSUE TITLE
900 after prior 9xx command doesn't behave correctly

### ISSUE THREAD

**Issue by asimilon** [arnaud-carre/LSPlayer#7]
`900` command should use the last `9xx` offset from a previous row.

I tested on PT2.3F on Amiga that this is what happens.

LSPlayer is just using `00` as the offset instead of any previous row.

The only time `900` should use a zero offset into the sample is if no prior `9xx` command has been used (tested on Amiga).

**Comment by arnaud-carre** [comment]
interesting! I should have a look at that. Do you have simple repro .MOD with obvious fail? ( makes things easier to debug for me)

**Comment by asimilon** [comment]
I can knock one up for you, give me a couple of days and I'll email you a link.
