### ISSUE TITLE
Preload a6 with $dff096 instead of $dff0a0

### ISSUE THREAD

**Issue by roger-wetzel** [arnaud-carre/LSPlayer#8]
Salut Arnaud

LightSpeedPlayer.asm:
If a6 is preloaded with $dff096 instead of $dff0a0 then the code size would be reduced by 2 bytes and a few cycles could be saved during one tick/frame.

line 105: **move.w d1,$96-$a0(a6)** then becomes **move.w d1,(a6)**

Am I right with this?

Best regards
Roger (Depeche/Spreadpoint)

**Comment by arnaud-carre** [comment]
Hi! you're right, 4 cycles win! But $dff0a0 is mainly for "insane" version. LightSpeedPlayer.asm is more the generic version. I prefer keep $dff0a0 for all versions (more coherent)

**Comment by roger-wetzel** [comment]
Ok. I understand that you want to keep it that way.
